In [57]:
import cv2
import numpy as np
import os

In [58]:
img = cv2.imread(r"justica1.jpg") # image read
re_img = cv2.resize(img, (500,700))
cv2.imshow("Rohan", re_img)         #image show
cv2.waitKey(0)                # image frame wait time - ms and 0 pass keyboard any key press
cv2.destroyAllWindows()          # all windows close 
# cv2.destroyWindow()              # only one window close

In [59]:
v = np.array([[1,2,3,1,2,3]])
np.hstack((v,v))

array([[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]])

In [60]:
img = cv2.imread(r"justica1.jpg") # image read
print(img) # RGB

[[[ 43  80 106]
  [ 43  80 106]
  [ 43  80 106]
  ...
  [ 14  34  49]
  [ 14  34  49]
  [ 14  34  49]]

 [[ 43  80 106]
  [ 43  80 106]
  [ 43  80 106]
  ...
  [ 14  34  49]
  [ 14  34  49]
  [ 14  34  49]]

 [[ 43  80 106]
  [ 43  80 106]
  [ 43  80 106]
  ...
  [ 14  34  49]
  [ 14  34  49]
  [ 14  34  49]]

 ...

 [[ 82  86  96]
  [ 82  86  96]
  [ 82  86  96]
  ...
  [  9  10  21]
  [  9  10  21]
  [  9  10  21]]

 [[ 82  86  96]
  [ 82  86  96]
  [ 82  86  96]
  ...
  [  9  10  21]
  [  9  10  21]
  [  9  10  21]]

 [[ 84  85  96]
  [ 84  85  96]
  [ 84  85  96]
  ...
  [  9  10  21]
  [  9  10  21]
  [  9  10  21]]]


In [ ]:
img = cv2.imread(r"justica2.jpg") # image read
re_img = cv2.resize(img, (300,300))
h = np.hstack((re_img,re_img,re_img))
v = np.vstack((h,h,h))
cv2.imshow("Rohan", v)         #image show
cv2.waitKey(0)                # image frame wait time - ms and 0 pass keyboard any key press
cv2.destroyAllWindows()          # all windows close 
# cv2.destroyWindow()              # only one window close

In [62]:
list_name = os.listdir(r"E:\Open CV image processing\test data")
list_name

['image read and show.ipynb', 'justica1.jpg', 'justica2.jpg', 'justica3.JPG']

In [73]:
list_name = os.listdir(r"E:\Open CV image processing\test data")
for name in list_name:
    img_path = os.path.join( name)
    img = cv2.imread(img_path)
    
    if img is None:
        print(f"Error loading: {img_path}")
        continue  # Skip invalid files
    
    img = cv2.resize(img, (500, 600))
    cv2.imshow("Rohan", img)
    cv2.waitKey(0)

cv2.destroyAllWindows()

Error loading: image read and show.ipynb
