In [5]:
import cv2
import numpy as np

In [6]:
img = cv2.imread(r"justica1.jpg") # image read
re_img = cv2.resize(img, (500,700))
cv2.imshow("Rohan", re_img)         #image show
cv2.waitKey(0)                # image frame wait time - ms and 0 pass keyboard any key press
cv2.destroyAllWindows()          # all windows close 
# cv2.destroyWindow()              # only one window close

In [10]:
v = np.array([[1,2,3,1,2,3]])
np.hstack((v,v))

array([[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]])

In [ ]:
img = cv2.imread(r"justica1.jpg") # image read
print(img) # RGB

[[[ 43  80 106]
  [ 43  80 106]
  [ 43  80 106]
  ...
  [ 14  34  49]
  [ 14  34  49]
  [ 14  34  49]]

 [[ 43  80 106]
  [ 43  80 106]
  [ 43  80 106]
  ...
  [ 14  34  49]
  [ 14  34  49]
  [ 14  34  49]]

 [[ 43  80 106]
  [ 43  80 106]
  [ 43  80 106]
  ...
  [ 14  34  49]
  [ 14  34  49]
  [ 14  34  49]]

 ...

 [[ 82  86  96]
  [ 82  86  96]
  [ 82  86  96]
  ...
  [  9  10  21]
  [  9  10  21]
  [  9  10  21]]

 [[ 82  86  96]
  [ 82  86  96]
  [ 82  86  96]
  ...
  [  9  10  21]
  [  9  10  21]
  [  9  10  21]]

 [[ 84  85  96]
  [ 84  85  96]
  [ 84  85  96]
  ...
  [  9  10  21]
  [  9  10  21]
  [  9  10  21]]]


In [17]:
img = cv2.imread(r"justica2.jpg") # image read
re_img = cv2.resize(img, (300,300))
h = np.hstack((re_img,re_img,re_img))
v = np.vstack((h,h,h))
cv2.imshow("Rohan", v)         #image show
cv2.waitKey(0)                # image frame wait time - ms and 0 pass keyboard any key press
cv2.destroyAllWindows()          # all windows close 
# cv2.destroyWindow()              # only one window close